### PR TITLE
Update version to 1.2.0

### PR DESCRIPTION
**Pull request by Jeff-Ciesielski**
Also: Change email/github pointers to keyme

### CODE REVIEW

**Comment by knitHacker** [comment]
LGTM

**Comment by penguinland** [comment]
LGTM. What repo is this?

**Comment by Jeff-Ciesielski** [comment]
@penguinland: A library I wrote a while back that we're now using in production.  Made sense to just absorb it here for ease of review :)

**Comment by kborer** [comment]
i_am_one

**Pull request merged**
